spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
telegram.bot.token=7480009755:AAGgGYuIs_-gSs2DlXfeHIsGrgRxb3lM2SE

# ????????? Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
